# Generated by Django 4.1.7 on 2023-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('struktura', models.TextField(blank=True)),
                ('dolzhnost', models.TextField(blank=True)),
                ('nomer', models.CharField(max_length=255)),
                ('existence', models.BooleanField(default=True)),
            ],
        ),
    ]
