# Generated by Django 4.1.7 on 2023-04-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Имя')),
                ('telephone', models.CharField(max_length=255, verbose_name='Номер телефона')),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='about',
            name='dolzhnost',
            field=models.TextField(blank=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='about',
            name='nomer',
            field=models.CharField(max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='about',
            name='struktura',
            field=models.TextField(blank=True, verbose_name='Структура'),
        ),
    ]
